### ISSUE TITLE
Should formatting functions take a DiffTime instead?

### ISSUE THREAD

**Issue by iustin** [pbrisbin/friendly-time#17]
Currently, the formatting function take a UTCTime, and internally do a diffUTCTime. This seems overly prescriptive, and if one already as a DiffTime around, it's not very helpful.

Since the function don't actually do anything with the absolute dates, just diff them, why don't they take as argument a DiffTime (or NominalDiffTime, etc.)?

**Comment by iustin** [comment]
Thinking some more, it probably comes from the "ago/in [the future]" part. But I think the duration computation is useful on its own without the direction (ago/in the future). So I'm wondering if it should be available separately as well (e.g. "the process took about one hour").

**Comment by pbrisbin** [comment]
For what it's worth, I've moved my own projects over to [`Formatting.Time`](https://hackage.haskell.org/package/formatting-6.3.7/docs/Formatting-Time.html#g:5). The interface is a little cumbersome, but you can produce the desired result.

I actually have an example of both styles you're referencing (I think):

```
          Succeeded
          #{format (diff True) $ diffUTCTime completedAt now}
          (took #{format (diff False) $ diffUTCTime (jobCreatedAt job) completedAt})
```

[source](https://github.com/restyled-io/restyled.io/blob/e3e0df79b45ffaef02cc400bd7aed097c23bfd1a/templates/widgets/job-card.hamlet#L17-L19)

Produces

> Succeeded **x minutes ago** (took **y seconds**)

**Comment by iustin** [comment]
Doh! I've been searching all over for a formatter for relative times, all the while not realising that formatting (which I already was using) supports this. Thanks a lot and sorry for the noise!
