### ISSUE TITLE
Consider listing friendly-time in Stackage

### ISSUE THREAD

**Issue by cies** [pbrisbin/friendly-time#9]
I find this a very useful package, and expect more and more (freely distributed) packages will depend on it (currently 2 [1]), as we will find more end-user facing code to be written in Haskell.  Currently I think mostly private projects depend on friendly-time.

Anyway, I given the uptake of Stackage lately, and the extra checks it offers on the compilability of packages I hope that you could consider to put list it on Stackage.

I'm currently working on an open source CMS based on Yesod [2] (to be announced on /r/haskell next month) which I also want to get included in Stackage.  Since it depends on friendly-time I want to ask you if it is okay if I become friendly-time's Stackage maintainer in case you are not interested in doing that.

Kindly,
Cies.

[1] http://packdeps.haskellers.com/reverse/friendly-time
[2] https://github.com/lambdacms

**Comment by pbrisbin** [comment]
> I want to ask you if it is okay if I become friendly-time's Stackage maintainer

Yes please!

I don't actively use this project any longer so anyone willing to step up with maintenance (the code, hackage, or stackage) is very welcome.

**Comment by cies** [comment]
:)  I hereby apply for maintainership. You might want to ask others as well (@league for instance).

**Comment by pbrisbin** [comment]
I've added you as a collaborator. Please feel free to make any packaging changes you need to get this on Stackage. All I ask is that if you want to make actual code changes or additions, they go by way of PR.

Thanks!
